server:
  port: 8080
  servlet:
    context-path: /accounts
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: "{cipher}db98873b84915bbd1b8f8945eb63c27bfab2948a5b91601ea86edfc416c81acb6db94d37fcddcccc01623d08145d8787febace6f732bc97b2805987abf3a62f8"
    username: "{cipher}60964411b8a01470964ffc1b612d45aed2aba671cfea89f72ea36fa7a8e17ce3"
    password: "{cipher}d561dc23d63b81962403467bbdcea2c0f3c1ff21ca5f6eb30417901db95b4bc0"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    sql:
      init:
        mode: always
    show-sql: true
  cloud:
    function:
      definition: updateDeliveryStatus
    stream:
      bindings:
        updateDeliveryStatus-in-0:
          destination: communication-sent
          group: ${spring.application.name}
        sendCommunication-out-0:
          destination: send-communication
config-management:
  name: 'DEFAULT'
  secretValue: "{cipher}2816379cef838ea5c03a85208d91c9deeda1cf0e49c4882e35b1265c0b1af259c5563cc15bb1a6979e3a9aebe43bd5587f62029ee8436ff83d270e7fe3a714c8"
  availability:
    - country: "Brazil"
      service: "Service6"
    - country: "Canada"
      service: "Service8"
logging:
  level:
    com:
      dalearner:
        accounts: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  info:
    env:
      enabled: true
