server:
  port: 9000
  servlet:
    context-path: /cards
spring:
  datasource:
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    sql:
      init:
        mode: always
    show-sql: true
