spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: accounts-service
          uri: http://accounts:8080
          predicates:
            - Path=/api/accounts/**
          filters:
            - RewritePath=/api/accounts/(?<segment>.*), /accounts/${segment}
        - id: loans-service
          uri: http://loans:8090
          predicates:
            - Path=/api/loans/**
          filters:
            - RewritePath=/api/loans/(?<segment>.*), /loans/${segment}
        - id: cards-service
          uri: http://cards:9000
          predicates:
            - Path=/api/cards/**
          filters:
            - RewritePath=/api/cards/(?<segment>.*), /cards/${segment}
