server:
  port: 8090
  servlet:
    context-path: /loans
spring:
  datasource:
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    sql:
      init:
        mode: always
    show-sql: true

config-management:
  name: 'LOANS-DEFAULT'
  secretValue: "{cipher}12ed3451626f34b2571000e50edb24bf5479e67c84be16ee2518fbf9e342eafe5dc499169f376b3f991cadf1ff2eaec7f558e444b5cdce5d19a69c7f56c22963"
  loansAvailability:
    - country: "Brazil"
      service: "Service6213"
    - country: "Canada"
      service: "Service834"
